name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-test:
    name: Run test script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.25
      - run: bun install
      - run: bun test
